source 'https://rubygems.org'
ruby '2.2.2'

# Please sort
gem 'rake'
gem 'ruboty-aa'
gem 'ruboty-alias'
gem 'ruboty-cron', '0.0.9'
gem 'ruboty-echo'
gem 'ruboty-github'
gem 'ruboty-google_image'
gem 'ruboty-japan_weather'
gem 'ruboty-kintai'
gem 'ruboty-kokodeikku'
gem 'ruboty-mpush'
gem 'ruboty-redis'
gem 'ruboty-reminder'
gem 'ruboty-sebastian', github: 'feedforce/ruboty-sebastian'
gem 'ruboty-slack'
gem 'ruboty-syoboi_calendar'
gem 'ruboty-talk'
gem 'ruboty-wareki'
