source 'https://rubygems.org'
ruby '2.2.2'

# Please sort
gem 'my_company-schedule'
gem 'rake'
gem 'ruboty-aa'
gem 'ruboty-alias'
gem 'ruboty-can_i_borrow'
gem 'ruboty-cron'
gem 'ruboty-echo'
gem 'ruboty-github'
gem 'ruboty-google_image'
gem 'ruboty-japan_weather'
gem 'ruboty-kintai'
gem 'ruboty-kokodeikku'
gem 'ruboty-mpush'
gem 'ruboty-redis'
gem 'ruboty-reminder'
gem 'ruboty-ruby'
gem 'ruboty-sebastian', github: 'feedforce/ruboty-sebastian'
gem 'ruboty-slack'
gem 'ruboty-syoboi_calendar'
gem 'ruboty-talk'
gem 'ruboty-wareki'
