version: 2.1

orbs:
  ruby-orbs: sue445/ruby-orbs@dev:380ce2184af53eff571a68d64b796713720e2d5b

workflows:
  version: 2

  nightly:
    jobs:
      - ruby-orbs/bundle-update-pr:
          filters:
            branches:
              only: introduce-continuous-bundle-update
          image: "circleci/ruby:2.3.3"
          pre-bundle-update-pr:
            - run:
                name: "Set timezone to Asia/Tokyo"
                command: "sudo cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime"
          git_user_name: "feedforce tech team"
          git_user_email: "technical_staff@feedforce.jp"
          github_access_token: "$GITHUB_ACCESS_TOKEN"
